
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: simon
  password: 123456
  host: localhost
  port: 5001

development:
  <<: *default
  database: morney_rails_2_development
test:
  <<: *default
  database: morney_rails_2_test
production:
  <<: *default
  database: morney_rails_2_production
  username: morney_rails_2
  password: <%= ENV['MORNEY_RAILS_2_DATABASE_PASSWORD'] %>
